package net.tropimon.tropitracker;

import java.util.HashMap;
import java.util.Map;

public class FrenchNames {

    private static final Map<String, String> NAMES = new HashMap<>();

    static {
        NAMES.put("abomasnow", "Blizzaroi"); NAMES.put("abra", "Abra"); NAMES.put("absol", "Absol");
        NAMES.put("accelgor", "Limaspeed"); NAMES.put("aegislash", "Exagide"); NAMES.put("aerodactyl", "Ptéra");
        NAMES.put("aggron", "Galeking"); NAMES.put("aipom", "Capumain"); NAMES.put("alakazam", "Alakazam");
        NAMES.put("alcremie", "Charmilly"); NAMES.put("alomomola", "Mamanbo"); NAMES.put("altaria", "Altaria");
        NAMES.put("amaura", "Amagara"); NAMES.put("ambipom", "Capidextre"); NAMES.put("amoonguss", "Gaulet");
        NAMES.put("ampharos", "Pharamp"); NAMES.put("annihilape", "Courrousinge"); NAMES.put("anorith", "Anorith");
        NAMES.put("appletun", "Dratatin"); NAMES.put("applin", "Verpom"); NAMES.put("araquanid", "Tarenbulle");
        NAMES.put("arbok", "Arbok"); NAMES.put("arboliva", "Arboliva"); NAMES.put("arcanine", "Arcanin");
        NAMES.put("arceus", "Arceus"); NAMES.put("archaludon", "Archaludon"); NAMES.put("archen", "Arkéapti");
        NAMES.put("archeops", "Aéroptéryx"); NAMES.put("arctibax", "Cryodo"); NAMES.put("arctovish", "Hydragla");
        NAMES.put("armarouge", "Carmadura"); NAMES.put("arrokuda", "Embrochet"); NAMES.put("articuno", "Artikodin");
        NAMES.put("audino", "Nanméouïe"); NAMES.put("aurorus", "Dragmara"); NAMES.put("avalugg", "Séracrawl");
        NAMES.put("axew", "Coupenotte"); NAMES.put("azelf", "Créfadet"); NAMES.put("azumarill", "Azumarill");
        NAMES.put("azurill", "Azurill"); NAMES.put("bagon", "Draby"); NAMES.put("baltoy", "Balbuto");
        NAMES.put("banette", "Branette"); NAMES.put("barbaracle", "Golgopathe"); NAMES.put("barboach", "Barloche");
        NAMES.put("barraskewda", "Hastacuda"); NAMES.put("basculegion", "Paragruel"); NAMES.put("basculin", "Bargantua");
        NAMES.put("bastiodon", "Bastiodon"); NAMES.put("bayleef", "Macronium"); NAMES.put("beartic", "Polagriffe");
        NAMES.put("beautifly", "Charmillon"); NAMES.put("beedrill", "Dardargnan"); NAMES.put("beheeyem", "Neitram");
        NAMES.put("beldum", "Terhal"); NAMES.put("bellibolt", "Ampibidou"); NAMES.put("bellsprout", "Chétiflor");
        NAMES.put("bergmite", "Grelaçon"); NAMES.put("bewear", "Chelours"); NAMES.put("bibarel", "Castorno");
        NAMES.put("bidoof", "Keunotor"); NAMES.put("bisharp", "Scalproie"); NAMES.put("blacephalon", "Pierroteknik");
        NAMES.put("blastoise", "Tortank"); NAMES.put("blaziken", "Braségali"); NAMES.put("blipbug", "Larvadar");
        NAMES.put("blissey", "Leuphorie"); NAMES.put("boltund", "Fulgudog"); NAMES.put("bombirdier", "Lestombaile");
        NAMES.put("bonsly", "Manzaï"); NAMES.put("bouffalant", "Frison"); NAMES.put("bounsweet", "Croquine");
        NAMES.put("brambleghast", "Virevorreur"); NAMES.put("bramblin", "Virovent"); NAMES.put("braviary", "Gueriaigle");
        NAMES.put("breloom", "Chapignon"); NAMES.put("bronzong", "Archéodong"); NAMES.put("bronzor", "Archéomire");
        NAMES.put("brute_bonnet", "Fongus-Furie"); NAMES.put("bruxish", "Denticrisse"); NAMES.put("budew", "Rozbouton");
        NAMES.put("buizel", "Mustébouée"); NAMES.put("bulbasaur", "Bulbizarre"); NAMES.put("buneary", "Laporeille");
        NAMES.put("bunnelby", "Sapereau"); NAMES.put("burmy", "Cheniti"); NAMES.put("butterfree", "Papilusion");
        NAMES.put("cacnea", "Cacnea"); NAMES.put("cacturne", "Cacturne"); NAMES.put("calyrex", "Sylveroy");
        NAMES.put("camerupt", "Camérupt"); NAMES.put("capsakid", "Pimito"); NAMES.put("carbink", "Strassie");
        NAMES.put("carnivine", "Vortente"); NAMES.put("carracosta", "Mégapagos"); NAMES.put("carvanha", "Carvanha");
        NAMES.put("castform", "Morphéo"); NAMES.put("caterpie", "Chenipan"); NAMES.put("celebi", "Celebi");
        NAMES.put("ceruledge", "Malvalame"); NAMES.put("cetitan", "Balbalèze"); NAMES.put("cetoddle", "Piétacé");
        NAMES.put("chandelure", "Lugulabre"); NAMES.put("chansey", "Leveinard"); NAMES.put("charizard", "Dracaufeu");
        NAMES.put("charjabug", "Chrysapile"); NAMES.put("charmander", "Salamèche"); NAMES.put("charmeleon", "Reptincel");
        NAMES.put("chesnaught", "Blindépique"); NAMES.put("chespin", "Marisson"); NAMES.put("chewtle", "Khélocrok");
        NAMES.put("chikorita", "Germignon"); NAMES.put("chimchar", "Ouisticram"); NAMES.put("chimecho", "Éoko");
        NAMES.put("chinchou", "Loupio"); NAMES.put("chingling", "Korillon"); NAMES.put("cinccino", "Pashmilla");
        NAMES.put("cinderace", "Pyrobut"); NAMES.put("clamperl", "Coquiperl"); NAMES.put("clauncher", "Flingouste");
        NAMES.put("clawitzer", "Gamblast"); NAMES.put("claydol", "Kaorine"); NAMES.put("clefable", "Mélodelfe");
        NAMES.put("clefairy", "Mélofée"); NAMES.put("cleffa", "Mélo"); NAMES.put("clobbopus", "Poulpaf");
        NAMES.put("clodsire", "Terraiste"); NAMES.put("cloyster", "Crustabri"); NAMES.put("coalossal", "Monthracite");
        NAMES.put("cobalion", "Cobaltium"); NAMES.put("cofagrigus", "Tutankafer"); NAMES.put("comfey", "Guérilande");
        NAMES.put("conkeldurr", "Bétochef"); NAMES.put("copperajah", "Pachyradjah"); NAMES.put("corviknight", "Corvaillus");
        NAMES.put("corvisquire", "Bleuseille"); NAMES.put("cosmoem", "Cosmovum"); NAMES.put("cosmog", "Cosmog");
        NAMES.put("cottonee", "Doudouvet"); NAMES.put("crabominable", "Crabominable"); NAMES.put("crabrawler", "Crabagarre");
        NAMES.put("cramorant", "Nigosier"); NAMES.put("cranidos", "Kranidos"); NAMES.put("crawdaunt", "Colhomard");
        NAMES.put("cresselia", "Cresselia"); NAMES.put("croagunk", "Cradopaud"); NAMES.put("crobat", "Nostenfer");
        NAMES.put("croconaw", "Crocrodil"); NAMES.put("crustle", "Crabaraque"); NAMES.put("cryogonal", "Hexagel");
        NAMES.put("cubchoo", "Polarhume"); NAMES.put("cubone", "Osselait"); NAMES.put("cufant", "Charibari");
        NAMES.put("cursola", "Corayôme"); NAMES.put("cutiefly", "Bombydou"); NAMES.put("cyndaquil", "Héricendre");
        NAMES.put("darkrai", "Darkrai"); NAMES.put("darmanitan", "Darumacho"); NAMES.put("dartrix", "Efflèche");
        NAMES.put("darumaka", "Darumarond"); NAMES.put("decidueye", "Archéduc"); NAMES.put("dedenne", "Dedenne");
        NAMES.put("deino", "Solochi"); NAMES.put("delcatty", "Delcatty"); NAMES.put("delibird", "Cadoizo");
        NAMES.put("delphox", "Goupelin"); NAMES.put("deoxys", "Deoxys"); NAMES.put("dewgong", "Lamantine");
        NAMES.put("dewott", "Mateloutre"); NAMES.put("dhelmise", "Sinistrail"); NAMES.put("dialga", "Dialga");
        NAMES.put("diancie", "Diancie"); NAMES.put("diggersby", "Excavarenne"); NAMES.put("diglett", "Taupiqueur");
        NAMES.put("ditto", "Métamorph"); NAMES.put("dodrio", "Dodrio"); NAMES.put("doduo", "Doduo");
        NAMES.put("dolliv", "Olivado"); NAMES.put("donphan", "Donphan"); NAMES.put("dracovish", "Hydragon");
        NAMES.put("dracozolt", "Galvagon"); NAMES.put("dragalge", "Kravarech"); NAMES.put("dragapult", "Lanssorien");
        NAMES.put("dragonair", "Draco"); NAMES.put("dragonite", "Dracolosse"); NAMES.put("drakloak", "Dispareptil");
        NAMES.put("drapion", "Drascore"); NAMES.put("dratini", "Minidraco"); NAMES.put("drednaw", "Torgamord");
        NAMES.put("dreepy", "Fantyrm"); NAMES.put("drifblim", "Grodrive"); NAMES.put("drifloon", "Baudrive");
        NAMES.put("drilbur", "Rototaupe"); NAMES.put("drizzile", "Arrozard"); NAMES.put("drowzee", "Soporifik");
        NAMES.put("orthworm", "Ferdeter");
        NAMES.put("druddigon", "Drakkarmin"); NAMES.put("dubwool", "Moumouflon"); NAMES.put("dugtrio", "Triopikeur");
        NAMES.put("dunsparce", "Insolourdo"); NAMES.put("duosion", "Méios"); NAMES.put("duraludon", "Duralugon");
        NAMES.put("durant", "Fermite"); NAMES.put("dusclops", "Téraclope"); NAMES.put("dusknoir", "Noctunoir");
        NAMES.put("duskull", "Skelénox"); NAMES.put("dustox", "Papinox"); NAMES.put("dwebble", "Crabicoque");
        NAMES.put("eelektrik", "Lampéroie"); NAMES.put("eelektross", "Ohmassacre"); NAMES.put("eevee", "Évoli");
        NAMES.put("electabuzz", "Élektek"); NAMES.put("electivire", "Élekable"); NAMES.put("electrike", "Dynavolt");
        NAMES.put("electrode", "Électrode"); NAMES.put("elekid", "Élekid"); NAMES.put("elgyem", "Lewsor");
        NAMES.put("emboar", "Roitiflam"); NAMES.put("emolga", "Emolga"); NAMES.put("empoleon", "Pingoléon");
        NAMES.put("entei", "Entei"); NAMES.put("escavalier", "Lançargot"); NAMES.put("espeon", "Mentali");
        NAMES.put("espurr", "Psystigri"); NAMES.put("eternatus", "Éthernatos"); NAMES.put("excadrill", "Minotaupe");
        NAMES.put("exeggcute", "Nœunoeuf"); NAMES.put("exeggutor", "Noadkoko"); NAMES.put("exploud", "Brouhabam");
        NAMES.put("falinks", "Hexadron"); NAMES.put("farfetchd", "Canarticho"); NAMES.put("farigiraf", "Farigiraf");
        NAMES.put("fearow", "Rapasdepic"); NAMES.put("feebas", "Barpau"); NAMES.put("fennekin", "Feunnec");
        NAMES.put("feraligatr", "Aligatueur"); NAMES.put("ferroseed", "Grindur"); NAMES.put("ferrothorn", "Noacier");
        NAMES.put("fidough", "Pâtachiot"); NAMES.put("flaaffy", "Lainergie"); NAMES.put("flabebe", "Flabébé");
        NAMES.put("flamigo", "Flamenroule"); NAMES.put("flapple", "Pomdrapi"); NAMES.put("fletchinder", "Braisillon");
        NAMES.put("fletchling", "Passerouge"); NAMES.put("floatzel", "Mustéflott"); NAMES.put("floette", "Floette");
        NAMES.put("florges", "Florges"); NAMES.put("flygon", "Libégon"); NAMES.put("fomantis", "Mimantis");
        NAMES.put("foongus", "Trompignon"); NAMES.put("forretress", "Foretress"); NAMES.put("fraxure", "Incisache");
        NAMES.put("frillish", "Viskuse"); NAMES.put("froakie", "Grenousse"); NAMES.put("frogadier", "Croâporal");
        NAMES.put("froslass", "Momartik"); NAMES.put("frosmoth", "Beldeneige"); NAMES.put("fuecoco", "Chochodile");
        NAMES.put("furfrou", "Couafarel"); NAMES.put("furret", "Fouinar"); NAMES.put("gabite", "Carmache");
        NAMES.put("gallade", "Gallame"); NAMES.put("galvantula", "Mygavolt"); NAMES.put("garbodor", "Miasmax");
        NAMES.put("garchomp", "Carchacrok"); NAMES.put("gardevoir", "Gardevoir"); NAMES.put("gastly", "Fantominus");
        NAMES.put("gastrodon", "Tritosor"); NAMES.put("genesect", "Génesect"); NAMES.put("gengar", "Ectoplasma");
        NAMES.put("geodude", "Racaillou"); NAMES.put("gholdengo", "Gromago"); NAMES.put("gible", "Griknot");
        NAMES.put("gigalith", "Gigalithe"); NAMES.put("gimmighoul", "Mordudor"); NAMES.put("giratina", "Giratina");
        NAMES.put("glaceon", "Givrali"); NAMES.put("glalie", "Oniglali"); NAMES.put("glameow", "Chaglam");
        NAMES.put("gligar", "Scorplane"); NAMES.put("glimmet", "Germéclat"); NAMES.put("glimmora", "Floréclat");
        NAMES.put("gliscor", "Scorvol"); NAMES.put("gloom", "Ortide"); NAMES.put("gogoat", "Chevroum");
        NAMES.put("golbat", "Nosferalto"); NAMES.put("goldeen", "Poissirène"); NAMES.put("golduck", "Akwakwak");
        NAMES.put("golem", "Grolem"); NAMES.put("golett", "Gringolem"); NAMES.put("golisopod", "Sarmuraï");
        NAMES.put("golurk", "Golemastoc"); NAMES.put("goodra", "Muplodocus"); NAMES.put("goomy", "Mucuscule");
        NAMES.put("gorebyss", "Rosabyss"); NAMES.put("gossifleur", "Tournicoton"); NAMES.put("gothita", "Scrutella");
        NAMES.put("gothitelle", "Sidérella"); NAMES.put("gothorita", "Mesmérella"); NAMES.put("grapploct", "Krakos");
        NAMES.put("graveler", "Gravalanch"); NAMES.put("greavard", "Toutombe"); NAMES.put("greninja", "Amphinobi");
        NAMES.put("grimer", "Tadmorv"); NAMES.put("grookey", "Ouistempo"); NAMES.put("grotle", "Boskara");
        NAMES.put("groudon", "Groudon"); NAMES.put("grovyle", "Massko"); NAMES.put("growlithe", "Caninos");
        NAMES.put("grubbin", "Larvibule"); NAMES.put("grumpig", "Groret"); NAMES.put("gulpin", "Gloupti");
        NAMES.put("gurdurr", "Ouvrifier"); NAMES.put("gyarados", "Léviator"); NAMES.put("happiny", "Ptiravi");
        NAMES.put("hariyama", "Hariyama"); NAMES.put("hatenna", "Bibichut"); NAMES.put("hatterene", "Sorcilence");
        NAMES.put("hattrem", "Chapotus"); NAMES.put("haunter", "Spectrum"); NAMES.put("hawlucha", "Brutalibré");
        NAMES.put("haxorus", "Tranchodon"); NAMES.put("heatmor", "Aflamanoir"); NAMES.put("heatran", "Heatran");
        NAMES.put("helioptile", "Galvaran"); NAMES.put("heliolisk", "Iguolta"); NAMES.put("heracross", "Scarhino");
        NAMES.put("herdier", "Ponchien"); NAMES.put("hippopotas", "Hippopotas"); NAMES.put("hippowdon", "Hippodocus");
        NAMES.put("hitmonchan", "Tygnon"); NAMES.put("hitmonlee", "Kicklee"); NAMES.put("hitmontop", "Kapoera");
        NAMES.put("ho_oh", "Ho-Oh"); NAMES.put("honchkrow", "Corboss"); NAMES.put("honedge", "Monorpale");
        NAMES.put("hoopa", "Hoopa"); NAMES.put("hoppip", "Granivol"); NAMES.put("horsea", "Hypotrempe");
        NAMES.put("houndoom", "Démolosse"); NAMES.put("houndour", "Malosse"); NAMES.put("huntail", "Serpang");
        NAMES.put("hydreigon", "Trioxhydre"); NAMES.put("hypno", "Hypnomade"); NAMES.put("igglybuff", "Toudoudou");
        NAMES.put("illumise", "Lumivole"); NAMES.put("incineroar", "Félinferno"); NAMES.put("indeedee", "Wimessir");
        NAMES.put("inteleon", "Lézargus"); NAMES.put("iron_boulder", "Roc-de-Fer");
        NAMES.put("iron_bundle", "Hotte-de-Fer"); NAMES.put("iron_hands", "Paume-de-Fer");
        NAMES.put("iron_jugulis", "Têtes-de-Fer"); NAMES.put("iron_leaves", "Vert-de-Fer");
        NAMES.put("iron_moth", "Mite-de-Fer"); NAMES.put("iron_thorns", "Épine-de-Fer");
        NAMES.put("iron_treads", "Roue-de-Fer"); NAMES.put("iron_valiant", "Garde-de-Fer");
        NAMES.put("iron_crown", "Chef-de-Fer"); NAMES.put("jellicent", "Moyade");
        NAMES.put("jigglypuff", "Rondoudou"); NAMES.put("jolteon", "Voltali"); NAMES.put("joltik", "Statitik");
        NAMES.put("jumpluff", "Cotovol"); NAMES.put("jynx", "Lippoutou"); NAMES.put("jirachi", "Jirachi");
        NAMES.put("kabuto", "Kabuto"); NAMES.put("kabutops", "Kabutops"); NAMES.put("kadabra", "Kadabra");
        NAMES.put("kakuna", "Coconfort"); NAMES.put("kartana", "Katagami"); NAMES.put("kecleon", "Kecleon");
        NAMES.put("kilowattrel", "Fulgulairo"); NAMES.put("kingambit", "Scalpereur"); NAMES.put("kingdra", "Hyporoi");
        NAMES.put("kingler", "Krabboss"); NAMES.put("kirlia", "Kirlia"); NAMES.put("klang", "Clic");
        NAMES.put("klawf", "Craparoi"); NAMES.put("klefki", "Trousselin"); NAMES.put("klink", "Tic");
        NAMES.put("klinklang", "Cliticlic"); NAMES.put("komala", "Komala"); NAMES.put("kommo_o", "Ékaïser");
        NAMES.put("koraidon", "Koraidon"); NAMES.put("krabby", "Krabby"); NAMES.put("kricketot", "Crikzik");
        NAMES.put("kricketune", "Mélokrik"); NAMES.put("krokorok", "Escroco"); NAMES.put("krookodile", "Crocorible");
        NAMES.put("kubfu", "Wushours"); NAMES.put("kyogre", "Kyogre"); NAMES.put("kyurem", "Kyurem");
        NAMES.put("landorus", "Démétéros"); NAMES.put("lanturn", "Lanturn"); NAMES.put("lapras", "Lokhlass");
        NAMES.put("larvesta", "Pyronille"); NAMES.put("larvitar", "Embrylex"); NAMES.put("latias", "Latias");
        NAMES.put("latios", "Latios"); NAMES.put("leafeon", "Phyllali"); NAMES.put("leavanny", "Manternel");
        NAMES.put("ledian", "Coxyclaque"); NAMES.put("ledyba", "Coxy"); NAMES.put("lickilicky", "Coudlangue");
        NAMES.put("lickitung", "Excelangue"); NAMES.put("liepard", "Léopardus"); NAMES.put("lileep", "Lilia");
        NAMES.put("lilligant", "Fragilady"); NAMES.put("lillipup", "Ponchiot"); NAMES.put("linoone", "Linéon");
        NAMES.put("litleo", "Hélionceau"); NAMES.put("litwick", "Funécire"); NAMES.put("lokix", "Gambex");
        NAMES.put("lombre", "Lombre"); NAMES.put("lopunny", "Lockpin"); NAMES.put("lotad", "Nénupiot");
        NAMES.put("loudred", "Ramboum"); NAMES.put("lucario", "Lucario"); NAMES.put("ludicolo", "Ludicolo");
        NAMES.put("lugia", "Lugia"); NAMES.put("lumineon", "Luminéon"); NAMES.put("lunala", "Lunala");
        NAMES.put("lunatone", "Séléroc"); NAMES.put("luvdisc", "Lovdisc"); NAMES.put("luxio", "Luxio");
        NAMES.put("luxray", "Luxray"); NAMES.put("machamp", "Mackogneur"); NAMES.put("machoke", "Machopeur");
        NAMES.put("machop", "Machoc"); NAMES.put("magby", "Magby"); NAMES.put("magcargo", "Volcaropod");
        NAMES.put("magikarp", "Magicarpe"); NAMES.put("magmar", "Magmar"); NAMES.put("magmortar", "Maganon");
        NAMES.put("magnemite", "Magnéti"); NAMES.put("magneton", "Magnéton"); NAMES.put("magnezone", "Magnézone");
        NAMES.put("mamoswine", "Mammochon"); NAMES.put("manaphy", "Manaphy"); NAMES.put("mandibuzz", "Vaututrice");
        NAMES.put("manectric", "Élecsprint"); NAMES.put("mankey", "Férosinge"); NAMES.put("mantine", "Démanta");
        NAMES.put("mantyke", "Babimanta"); NAMES.put("maractus", "Maracachi"); NAMES.put("mareanie", "Vorastérie");
        NAMES.put("mareep", "Wattouat"); NAMES.put("marill", "Marill"); NAMES.put("marowak", "Ossatueur");
        NAMES.put("marshadow", "Marshadow"); NAMES.put("masquerain", "Maskadra"); NAMES.put("mawile", "Mysdibule");
        NAMES.put("medicham", "Charmina"); NAMES.put("meditite", "Méditikka"); NAMES.put("meganium", "Méganium");
        NAMES.put("melmetal", "Melmetal"); NAMES.put("meltan", "Meltan"); NAMES.put("meowscarada", "Miascarade");
        NAMES.put("meowth", "Miaouss"); NAMES.put("mesprit", "Créfollet"); NAMES.put("metagross", "Métalosse");
        NAMES.put("metang", "Métang"); NAMES.put("metapod", "Chrysacier"); NAMES.put("mew", "Mew");
        NAMES.put("mewtwo", "Mewtwo"); NAMES.put("mienfoo", "Kungfouine"); NAMES.put("mienshao", "Shaofouine");
        NAMES.put("mightyena", "Grahyèna"); NAMES.put("milcery", "Crèmy"); NAMES.put("milotic", "Milobellus");
        NAMES.put("mimejr", "Mime Jr."); NAMES.put("mimikyu", "Mimiqui"); NAMES.put("minccino", "Chinchidou");
        NAMES.put("minun", "Négapi"); NAMES.put("miraidon", "Miraidon"); NAMES.put("misdreavus", "Feuforêve");
        NAMES.put("mismagius", "Magirêve"); NAMES.put("moltres", "Sulfura"); NAMES.put("monferno", "Chimpenfeu");
        NAMES.put("morelull", "Spododo"); NAMES.put("morgrem", "Fourbelin"); NAMES.put("morpeko", "Morpeko");
        NAMES.put("mothim", "Papilord"); NAMES.put("mr_mime", "M. Mime"); NAMES.put("mr_rime", "M. Glaquette");
        NAMES.put("mudkip", "Gobou"); NAMES.put("mudsdale", "Bourrinos"); NAMES.put("murkrow", "Cornèbre");
        NAMES.put("musharna", "Mushana"); NAMES.put("naclstack", "Amassel"); NAMES.put("nacli", "Selutin");
        NAMES.put("naganadel", "Mandrillon"); NAMES.put("natu", "Natu"); NAMES.put("necrozma", "Necrozma");
        NAMES.put("nickit", "Goupilou"); NAMES.put("nidoking", "Nidoking"); NAMES.put("nidoqueen", "Nidoqueen");
        NAMES.put("nidoran_f", "Nidoran♀"); NAMES.put("nidoran_m", "Nidoran♂");
        NAMES.put("nidorina", "Nidorina"); NAMES.put("nidorino", "Nidorino"); NAMES.put("nihilego", "Zéroïd");
        NAMES.put("nincada", "Ningale"); NAMES.put("ninetales", "Feunard"); NAMES.put("ninjask", "Ninjask");
        NAMES.put("noctowl", "Noarfang"); NAMES.put("noibat", "Sonistrelle"); NAMES.put("noivern", "Bruyverne");
        NAMES.put("numel", "Chamallot"); NAMES.put("nuzleaf", "Pifeuil"); NAMES.put("octillery", "Octillery");
        NAMES.put("oddish", "Mystherbe"); NAMES.put("oinkologne", "Fragroin"); NAMES.put("omanyte", "Amonita");
        NAMES.put("omastar", "Amonistar"); NAMES.put("onix", "Onix"); NAMES.put("oranguru", "Gouroutan");
        NAMES.put("orbeetle", "Astronelle"); NAMES.put("oricorio", "Plumeline"); NAMES.put("oshawott", "Moustillon");
        NAMES.put("overqwil", "Qwilpik"); NAMES.put("pachirisu", "Pachirisu"); NAMES.put("palkia", "Palkia");
        NAMES.put("palossand", "Trépassable"); NAMES.put("palpitoad", "Batracné"); NAMES.put("pancham", "Pandespiègle");
        NAMES.put("pangoro", "Pandarbare"); NAMES.put("panpour", "Flotajou"); NAMES.put("pansage", "Feuillajou");
        NAMES.put("pansear", "Flamajou"); NAMES.put("paras", "Paras"); NAMES.put("parasect", "Parasect");
        NAMES.put("passimian", "Quartermac"); NAMES.put("pawmi", "Pohm"); NAMES.put("pawmot", "Pohmarmotte");
        NAMES.put("pawniard", "Scalpion"); NAMES.put("pecharunt", "Pêchaminus"); NAMES.put("pelipper", "Bekipan");
        NAMES.put("persian", "Persian"); NAMES.put("petilil", "Chlorobule"); NAMES.put("phantump", "Brocélôme");
        NAMES.put("pheromosa", "Cancrelove"); NAMES.put("phione", "Phione"); NAMES.put("pichu", "Pichu");
        NAMES.put("pidgeot", "Roucarnage"); NAMES.put("pidgeotto", "Roucoups"); NAMES.put("pidgey", "Roucool");
        NAMES.put("pidove", "Poichigeon"); NAMES.put("pikachu", "Pikachu"); NAMES.put("pikipek", "Picassaut");
        NAMES.put("piloswine", "Cochignon"); NAMES.put("pincurchin", "Wattapik"); NAMES.put("pinsir", "Scarabrute");
        NAMES.put("piplup", "Tiplouf"); NAMES.put("plusle", "Posipi"); NAMES.put("poipole", "Vémini");
        NAMES.put("polteageist", "Polthégeist"); NAMES.put("poliwag", "Ptitard"); NAMES.put("poliwhirl", "Têtarte");
        NAMES.put("poliwrath", "Tartard"); NAMES.put("ponyta", "Ponyta"); NAMES.put("poochyena", "Medhyèna");
        NAMES.put("porygon", "Porygon"); NAMES.put("porygon2", "Porygon2"); NAMES.put("porygon_z", "Porygon-Z");
        NAMES.put("primeape", "Colossinge"); NAMES.put("primarina", "Oratoria"); NAMES.put("prinplup", "Prinplouf");
        NAMES.put("probopass", "Tarinorme"); NAMES.put("psyduck", "Psykokwak"); NAMES.put("pupitar", "Ymphect");
        NAMES.put("purugly", "Chaffreux"); NAMES.put("pyroar", "Némélios"); NAMES.put("pyukumuku", "Concombaffe");
        NAMES.put("quaquaval", "Palmaval"); NAMES.put("quaxly", "Coiffeton"); NAMES.put("quaxwell", "Canarbello");
        NAMES.put("qwilfish", "Qwilfish"); NAMES.put("rabsca", "Bérasca"); NAMES.put("raichu", "Raichu");
        NAMES.put("raikou", "Raikou"); NAMES.put("ralts", "Tarsal"); NAMES.put("rampardos", "Charkos");
        NAMES.put("rapidash", "Galopa"); NAMES.put("raticate", "Rattatac"); NAMES.put("rattata", "Rattata");
        NAMES.put("rayquaza", "Rayquaza"); NAMES.put("regice", "Regice"); NAMES.put("regidrago", "Regidrago");
        NAMES.put("regieleki", "Regieleki"); NAMES.put("regigigas", "Regigigas"); NAMES.put("regirock", "Regirock");
        NAMES.put("registeel", "Registeel"); NAMES.put("relicanth", "Relicanth"); NAMES.put("rellor", "Léboulérou");
        NAMES.put("remoraid", "Rémoraid"); NAMES.put("reshiram", "Reshiram"); NAMES.put("reuniclus", "Symbios");
        NAMES.put("rhyhorn", "Rhinocorne"); NAMES.put("rhydon", "Rhinoféros"); NAMES.put("rhyperior", "Rhinastoc");
        NAMES.put("ribombee", "Rubombelle"); NAMES.put("riolu", "Riolu"); NAMES.put("rockruff", "Rocabot");
        NAMES.put("roggenrola", "Nodulithe"); NAMES.put("rookidee", "Minisange"); NAMES.put("roselia", "Rosélia");
        NAMES.put("roserade", "Roserade"); NAMES.put("rotom", "Motisma"); NAMES.put("rufflet", "Furaiglon");
        NAMES.put("runerigus", "Tutétékri"); NAMES.put("salandit", "Tritox"); NAMES.put("salazzle", "Malamandre");
        NAMES.put("samurott", "Samorott"); NAMES.put("sandaconda", "Dunaconda"); NAMES.put("sandile", "Mascaïman");
        NAMES.put("sandshrew", "Sabelette"); NAMES.put("sandslash", "Sablaireau"); NAMES.put("sandygast", "Bacabouh");
        NAMES.put("sawk", "Karaclée"); NAMES.put("sawsbuck", "Haydaim"); NAMES.put("scatterbug", "Lépidonille");
        NAMES.put("sceptile", "Jungko"); NAMES.put("scizor", "Cizayox"); NAMES.put("scorbunny", "Flambino");
        NAMES.put("scrafty", "Baggaïd"); NAMES.put("scraggy", "Baggiguane"); NAMES.put("scream_tail", "Hurle-Queue");
        NAMES.put("scyther", "Insécateur"); NAMES.put("seadra", "Hypocéan"); NAMES.put("seaking", "Poissoroy");
        NAMES.put("sealeo", "Phogleur"); NAMES.put("seedot", "Grainipiot"); NAMES.put("seel", "Otaria");
        NAMES.put("sentret", "Fouinette"); NAMES.put("serperior", "Majaspic"); NAMES.put("servine", "Lianaja");
        NAMES.put("seviper", "Séviper"); NAMES.put("shaymin", "Shaymin"); NAMES.put("shedinja", "Munja");
        NAMES.put("shelgon", "Drackhaus"); NAMES.put("shellder", "Kokiyas"); NAMES.put("shellos", "Sancoki");
        NAMES.put("shelmet", "Escargaume"); NAMES.put("shieldon", "Dinoclier"); NAMES.put("shiinotic", "Lampignon");
        NAMES.put("shiftry", "Tengalice"); NAMES.put("shinx", "Lixy"); NAMES.put("shroodle", "Gribouraigne");
        NAMES.put("shuckle", "Caratroc"); NAMES.put("shuppet", "Polichombr"); NAMES.put("sigilyph", "Cryptéro");
        NAMES.put("silvally", "Silvallié"); NAMES.put("sinistea", "Théffroi"); NAMES.put("sirfetchd", "Palarticho");
        NAMES.put("sizzlipede", "Grillepattes"); NAMES.put("skarmory", "Airmure"); NAMES.put("skeledirge", "Flâmigator");
        NAMES.put("skiddo", "Cabriolaine"); NAMES.put("skiploom", "Floravol"); NAMES.put("skitty", "Skitty");
        NAMES.put("skrelp", "Venalgue"); NAMES.put("skuntank", "Moufflair"); NAMES.put("slaking", "Monaflèmit");
        NAMES.put("slakoth", "Parecool"); NAMES.put("sliggoo", "Colimucus"); NAMES.put("slowbro", "Flagadoss");
        NAMES.put("slowking", "Roigada"); NAMES.put("slowpoke", "Ramoloss"); NAMES.put("slugma", "Limagma");
        NAMES.put("slurpuff", "Cupcanaille"); NAMES.put("smeargle", "Queulorior"); NAMES.put("smoliv", "Olivini");
        NAMES.put("smoochum", "Lippouti"); NAMES.put("sneasel", "Farfuret"); NAMES.put("sneasler", "Farfurex");
        NAMES.put("snivy", "Vipélierre"); NAMES.put("snorlax", "Ronflex"); NAMES.put("snorunt", "Stalgamin");
        NAMES.put("snover", "Blizzi"); NAMES.put("snubbull", "Snubbull"); NAMES.put("sobble", "Larméléon");
        NAMES.put("solgaleo", "Solgaleo"); NAMES.put("solosis", "Nucléos"); NAMES.put("solrock", "Solaroc");
        NAMES.put("spearow", "Piafabec"); NAMES.put("spectrier", "Spectreval"); NAMES.put("spewpa", "Pérégrain");
        NAMES.put("spheal", "Obalie"); NAMES.put("spinarak", "Mimigal"); NAMES.put("spinda", "Spinda");
        NAMES.put("spiritomb", "Spiritomb"); NAMES.put("spoink", "Spoink"); NAMES.put("spritzee", "Fluvetin");
        NAMES.put("squawkabilly", "Tapatoès"); NAMES.put("squirtle", "Carapuce"); NAMES.put("stakataka", "Ama-Ama");
        NAMES.put("stantler", "Cerfrousse"); NAMES.put("staraptor", "Étouraptor"); NAMES.put("staravia", "Étourvol");
        NAMES.put("starly", "Étourmi"); NAMES.put("starmie", "Staross"); NAMES.put("staryu", "Stari");
        NAMES.put("steelix", "Steelix"); NAMES.put("steenee", "Candine"); NAMES.put("stonjourner", "Dolman");
        NAMES.put("stoutland", "Mastouffe"); NAMES.put("stufful", "Nounourson"); NAMES.put("stunfisk", "Limonde");
        NAMES.put("stunky", "Moufouette"); NAMES.put("sudowoodo", "Simularbre"); NAMES.put("suicune", "Suicune");
        NAMES.put("sunflora", "Héliatronc"); NAMES.put("sunkern", "Tournegrin"); NAMES.put("surskit", "Arakdo");
        NAMES.put("swablu", "Tylton"); NAMES.put("swampert", "Laggron"); NAMES.put("swanna", "Lakmécygne");
        NAMES.put("swinub", "Marcacrin"); NAMES.put("swirlix", "Sucroquin"); NAMES.put("sylveon", "Nymphali");
        NAMES.put("taillow", "Nirondelle"); NAMES.put("talonflame", "Flambusard"); NAMES.put("tandemaus", "Compagnol");
        NAMES.put("tangela", "Saquedeneu"); NAMES.put("tangrowth", "Bouldeneu"); NAMES.put("tarountula", "Tissenboule");
        NAMES.put("tatsugiri", "Nigirigon"); NAMES.put("tauros", "Tauros"); NAMES.put("teddiursa", "Teddiursa");
        NAMES.put("tentacool", "Tentacool"); NAMES.put("tentacruel", "Tentacruel"); NAMES.put("tepig", "Gruikui");
        NAMES.put("terrakion", "Terrakium"); NAMES.put("thievul", "Roublenard"); NAMES.put("throh", "Judokrak");
        NAMES.put("thundurus", "Fulguris"); NAMES.put("tinkatink", "Forgerette"); NAMES.put("tinkatuff", "Forgella");
        NAMES.put("tinkaton", "Forgelina"); NAMES.put("tirtouga", "Carapagos"); NAMES.put("toedscool", "Terracool");
        NAMES.put("timburr", "Charpenti"); NAMES.put("blitzle", "Zébibron");
        NAMES.put("toedscruel", "Terracruel"); NAMES.put("togekiss", "Togekiss"); NAMES.put("togepi", "Togepi");
        NAMES.put("togetic", "Togetic"); NAMES.put("torchic", "Poussifeu"); NAMES.put("torkoal", "Chartor");
        NAMES.put("tornadus", "Boréas"); NAMES.put("torracat", "Matoufeu"); NAMES.put("torterra", "Torterra");
        NAMES.put("totodile", "Kaiminus"); NAMES.put("toxapex", "Prédastérie"); NAMES.put("toxel", "Toxizap");
        NAMES.put("toxicroak", "Coatox"); NAMES.put("toxtricity", "Salarsen"); NAMES.put("tranquill", "Colombeau");
        NAMES.put("trapinch", "Kraknoix"); NAMES.put("treecko", "Arcko"); NAMES.put("trevenant", "Desséliande");
        NAMES.put("tropius", "Tropius"); NAMES.put("trubbish", "Miamiasme"); NAMES.put("trumbeak", "Piclairon");
        NAMES.put("tsareena", "Sucreine"); NAMES.put("turtwig", "Tortipouss"); NAMES.put("tympole", "Tritonde");
        NAMES.put("tynamo", "Anchwatt"); NAMES.put("type_null", "Type:0"); NAMES.put("tyranitar", "Tyranocif");
        NAMES.put("tyrantrum", "Rexillius"); NAMES.put("tyrogue", "Debugant"); NAMES.put("umbreon", "Noctali");
        NAMES.put("unfezant", "Déflaisan"); NAMES.put("unown", "Zarbi"); NAMES.put("ursaluna", "Ursaking");
        NAMES.put("ursaring", "Ursaring"); NAMES.put("urshifu", "Shifours"); NAMES.put("uxie", "Créhelf");
        NAMES.put("vanillish", "Sorboul"); NAMES.put("vanillite", "Sorbébé"); NAMES.put("vanilluxe", "Sorbouboul");
        NAMES.put("vaporeon", "Aquali"); NAMES.put("venipede", "Venipatte"); NAMES.put("venomoth", "Aéromite");
        NAMES.put("venonat", "Mimitoss"); NAMES.put("venusaur", "Florizarre"); NAMES.put("vespiquen", "Apireine");
        NAMES.put("vibrava", "Vibraninf"); NAMES.put("victini", "Victini"); NAMES.put("vigoroth", "Vigoroth");
        NAMES.put("vikavolt", "Lucanon"); NAMES.put("vileplume", "Rafflesia"); NAMES.put("virizion", "Viridium");
        NAMES.put("vivillon", "Prismillon"); NAMES.put("volbeat", "Muciole"); NAMES.put("volcanion", "Volcanion");
        NAMES.put("volcarona", "Pyrax"); NAMES.put("voltorb", "Voltorbe"); NAMES.put("vullaby", "Vostourno");
        NAMES.put("vulpix", "Goupix"); NAMES.put("wailmer", "Wailmer"); NAMES.put("wailord", "Wailord");
        NAMES.put("walrein", "Kaimorse"); NAMES.put("wartortle", "Carabaffe"); NAMES.put("watchog", "Miradar");
        NAMES.put("weavile", "Dimoret"); NAMES.put("weedle", "Aspicot"); NAMES.put("weepinbell", "Boustiflor");
        NAMES.put("weezing", "Smogogo"); NAMES.put("whimsicott", "Farfaduvet"); NAMES.put("whirlipede", "Scobolide");
        NAMES.put("whiscash", "Barbicha"); NAMES.put("wigglytuff", "Grodoudou"); NAMES.put("wishiwashi", "Froussardine");
        NAMES.put("wobbuffet", "Qulbutoké"); NAMES.put("wooper", "Axoloto"); NAMES.put("wormadam", "Cheniselle");
        NAMES.put("wurmple", "Chenipotte"); NAMES.put("xatu", "Xatu"); NAMES.put("xerneas", "Xerneas");
        NAMES.put("xurkitree", "Câblifère"); NAMES.put("yamask", "Tutafeh"); NAMES.put("yamper", "Voltoutou");
        NAMES.put("yanma", "Yanma"); NAMES.put("yanmega", "Yanméga"); NAMES.put("yveltal", "Yveltal");
        NAMES.put("zangoose", "Mangriff"); NAMES.put("zapdos", "Électhor"); NAMES.put("zarude", "Zarude");
        NAMES.put("zebstrika", "Zéblitz"); NAMES.put("zekrom", "Zekrom"); NAMES.put("zeraora", "Zeraora");
        NAMES.put("zigzagoon", "Zigzaton"); NAMES.put("zoroark", "Zoroark"); NAMES.put("zorua", "Zorua");
        NAMES.put("zubat", "Nosferapti"); NAMES.put("zweilous", "Diamat"); NAMES.put("zygarde", "Zygarde");
        NAMES.put("flutter_mane", "Flotte-Mèche"); NAMES.put("slither_wing", "Rampe-Ailes");
        NAMES.put("sandy_shocks", "Pelage-Sablé"); NAMES.put("roaring_moon", "Rugit-Lune");
        NAMES.put("walking_wake", "Serpente-Eau"); NAMES.put("gouging_fire", "Feu-Perçant");
        NAMES.put("raging_bolt", "Ire-Foudre"); NAMES.put("great_tusk", "Fort-Ivoire");
    }

    public static String get(String englishName) {
        return NAMES.get(englishName.toLowerCase().replace("-", "_").replace(" ", "_"));
    }

    private static final Map<String, String> REVERSE = new HashMap<>();
    static {
        for (Map.Entry<String, String> entry : NAMES.entrySet()) {
            REVERSE.putIfAbsent(entry.getValue().toLowerCase(), entry.getKey());
        }
    }

    /** Résout un nom français (ex: "Crabicoque") vers le nom d'espèce anglais en minuscule (ex: "crustle"). */
    public static String getEnglishName(String frenchName) {
        if (frenchName == null) return null;
        return REVERSE.get(frenchName.toLowerCase());
    }
}
